load(
      "@rules_cc//cc:defs.bzl"
   ,  "cc_library"
)

cc_library(
      name       = "aapFunctionalCluster_VehicleUpdateAndConfigurationManagement"
   ,  srcs       = ["aapFunctionalCluster_VehicleUpdateAndConfigurationManagement.cpp"]
#  ,  deps       = ["//repo_projects/pProjectFull/main_LATEST/source/SwcServiceEcuM:SwcServiceEcuM"]
   ,  hdrs       = [
            "interface_VehicleUpdateAndConfigurationManagement_VehicleDriverApplication.hpp"
         ,  "interface_VehicleUpdateAndConfigurationManagement_VehiclePackageManagement.hpp"
         ,  "interface_VehicleUpdateAndConfigurationManagement_VehicleStateManager.hpp"
      ]
   ,  includes   = ["."]
   ,  visibility = ["//visibility:public"]
)

